# Generated by Django 5.0.4 on 2024-04-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮箱')),
                ('usertype', models.CharField(choices=[('1', '科研工作者'), ('2', '审核者'), ('3', '企业')], default='1', max_length=2, verbose_name='用户类型')),
                ('balance', models.IntegerField(default=100000, verbose_name='账户余额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录时间')),
                ('has_confirmed', models.BooleanField(default=False, verbose_name='是否邮箱验证')),
            ],
            options={
                'verbose_name': '网站用户管理',
                'verbose_name_plural': '网站用户管理',
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='确认码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.siteuser')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-create_time'],
            },
        ),
    ]
