# Generated by Django 5.0.4 on 2024-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='department',
            field=models.CharField(default=0, max_length=128, verbose_name='所属部门'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteuser',
            name='organization',
            field=models.CharField(default='公司', max_length=128, verbose_name='所属机构'),
            preserve_default=False,
        ),
    ]
