# Generated by Django 5.0.4 on 2024-04-21 02:40

import create.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('AchievementID', models.AutoField(primary_key=True, serialize=False, verbose_name='成果ID')),
                ('Title', models.CharField(max_length=200, verbose_name='标题')),
                ('Author', models.CharField(max_length=200, verbose_name='作者')),
                ('Ownership', models.CharField(max_length=200, verbose_name='所有权归属')),
                ('Abstract', models.TextField(verbose_name='摘要')),
                ('Keywords', models.CharField(max_length=200, verbose_name='关键词')),
                ('AchievementType', models.CharField(choices=[('1', '论文'), ('2', '专利'), ('3', '软件'), ('4', '技术报告')], default='1', max_length=200, verbose_name='成果类型')),
                ('ResearchStatus', models.CharField(choices=[('1', '未审核'), ('2', '已修改'), ('3', '审核中'), ('4', '待交易'), ('5', '交易中'), ('6', '已交易')], default='1', max_length=200, verbose_name='成果状态')),
                ('Price', models.FloatField(default=0, verbose_name='定价')),
                ('UploadTime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('ReadingCount', models.IntegerField(default=0, verbose_name='被查看次数')),
                ('CitingCount', models.IntegerField(default=0, verbose_name='被引用次数')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.siteuser', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '科研成果',
                'verbose_name_plural': '科研成果',
                'ordering': ['-UploadTime'],
            },
        ),
        migrations.CreateModel(
            name='ResearchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=create.models.get_upload_to, verbose_name='附件')),
                ('research_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='create.researchresult')),
            ],
            options={
                'verbose_name': '科研成果附件',
                'verbose_name_plural': '科研成果附件',
                'ordering': ['-id'],
            },
        ),
    ]
