# Generated by Django 5.0.4 on 2024-04-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrecords',
            name='ReviewResult',
            field=models.CharField(max_length=200, verbose_name='审核结果'),
        ),
    ]
