# Generated by Django 5.0.4 on 2024-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_reviewrecords_reviewresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrecords',
            name='ReviewResult',
            field=models.CharField(choices=[('1', '通过'), ('2', '未通过'), ('3', '未处理')], default='3', max_length=200, verbose_name='审核结果'),
        ),
    ]
